# Generated by Django 2.2.2 on 2019-07-12 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        )
    ]
