# Generated by Django 2.2.5 on 2020-07-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_betterself_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_writeup_user",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="signed_up_from",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "N/A"),
                    ("writeup", "WriteUp"),
                    ("betterself", "BetterSelf"),
                ],
                default="writeup",
                max_length=255,
            ),
        ),
    ]
