# Generated by Django 2.2.5 on 2020-07-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_user_signup_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_writeup_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="signed_up_from",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "N/A"),
                    ("writeup", "WriteUp"),
                    ("betterself", "BetterSelf"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]
