# Generated by Django 2.2.13 on 2020-08-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_created_modified_to_user"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ["-id"]},),
    ]
