# Generated by Django 2.2.4 on 2019-08-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_writeup_shared_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="WriteUpFlaggedPrompt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WriteUpPrompt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("title", models.TextField(blank=True, default="")),
                ("email", models.TextField(blank=True, default="")),
                ("instagram", models.TextField(blank=True, default="")),
                ("twitter", models.TextField(blank=True, default="")),
                ("website", models.TextField(blank=True, default="")),
                (
                    "share_state",
                    django_fsm.FSMField(
                        choices=[
                            ("unshared", "UNSHARED"),
                            (
                                "published_link_access_only",
                                "PUBLISHED_LINK_ACCESS_ONLY",
                            ),
                            ("published", "PUBLISHED"),
                        ],
                        default="unshared",
                        max_length=50,
                    ),
                ),
                (
                    "staff_verified_share_state",
                    django_fsm.FSMField(
                        choices=[
                            ("verified_fail", "Verified Fail"),
                            ("verified_pass", "Verified Pass"),
                            ("unverified_issue_multiple", "Unverified Issue Multiple"),
                            ("unverified_issue", "Unverified Issue"),
                            ("unverified", "Unverified"),
                        ],
                        default="unverified",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="WriteUpPromptVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("value", models.IntegerField(default=1)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.WriteUpPrompt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("prompt", "user")}},
        ),
        migrations.DeleteModel(name="WriteUpSharedPrompt"),
        migrations.AddField(
            model_name="writeupflaggedprompt",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.WriteUpPrompt"
            ),
        ),
        migrations.AddField(
            model_name="writeupflaggedprompt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="writeupflaggedprompt", unique_together={("prompt", "user")}
        ),
    ]
