# Generated by Django 2.2.4 on 2019-08-20 06:34

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [("core", "0003_add_score_to_prompt_model")]

    operations = [
        migrations.AddField(
            model_name="writeupprompt",
            name="content",
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict),
        )
    ]
