# Generated by Django 2.2.13 on 2020-07-06 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_betterself_models_part_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="ingredientcomposition",
            name="measurement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Measurement"
            ),
        ),
        migrations.AlterField(
            model_name="ingredientcomposition",
            name="quantity",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
    ]
