# Generated by Django 2.2.13 on 2020-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_supp_stack_and_compositions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
