# Generated by Django 2.2.13 on 2020-08-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_pomodoro_count_to_productivity_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="duration_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
