# Generated by Django 2.2.13 on 2020-08-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_null_duration_minutes_activity_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplement",
            name="is_taken_with_food",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
