# Generated by Django 2.2.13 on 2020-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_dailyproductivitylog_mistakes"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplementlog",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
