NO_ANSWER_CHOICE_TUPLE = ("", "N/A")
# Used to determine where a user signed up from
WRITEUP_APPLICATION_NAME = "WriteUp"
BETTERSELF_APPLICATION_NAME = "BetterSelf"

WRITEUP_APPLICATION_KEY = "writeup"
BETTERSELF_APPLICATION_KEY = "betterself"


SIGNED_UP_FROM_DETAILS_CHOICE = (
    NO_ANSWER_CHOICE_TUPLE,
    (WRITEUP_APPLICATION_KEY, WRITEUP_APPLICATION_NAME),
    (BETTERSELF_APPLICATION_KEY, BETTERSELF_APPLICATION_NAME),
)
